server {
    listen 80;
    
    # Serve the React Dashboard
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Automatically route API calls to the Backend container
    location /alerts {
        proxy_pass http://backend:8000/alerts;
    }
}